projectID: "base-dev-v3"
kinds:
  - name: "goalsConfig"
    namespace: "nsCommonDev"
#  - name: "goals"
#    namespace: "nsGlobalPavenDev"
  - name: "pages"
    namespace: "nsCommonDev"
  - name: "variables"
    namespace: "nsCommonDev"
#  - name: "vehicleConfig"
#    namespace: "nsCommonDev"
#  - name: "onboarding"
#    namespace: "nsGlobalPavenDev"